FROM nginx:alpine

RUN adduser -D nginx && echo "nginx:DevOps321" | chpasswd

RUN rm -rf /usr/share/nginx/html/*

COPY index.html /usr/share/nginx/html/index.html

USER nginx

ENTRYPOINT ["nginx", "-g", "daemon off;"]