FROM nginx

RUN adduser nginx && echo "nginx:DevOps321" | chpasswd

RUN rm -rf /usr/share/nginx/html/*

COPY nginx.html /usr/share/nginx/html/index.html

USER nginx

ENTRYPOINT ["nginx", "-g", "daemon off;"]

